### ISSUE TITLE
Transactions not showing details from blockchain when clicked in TonChan

### ISSUE THREAD

**Issue by StoopidWirez** [turtlecoin/turtlecoin-mobile-wallet#135]
**Describe the bug**
When attempting to view advance transaction data, the TonChan app immediately shuts down. Also, have one (very first) txn that never went through but shows in my transactions list

**To Reproduce**
1. Go to Transactions tab of TonChan wallet app
2. Click on any transaction
3. Immediately shuts app down

**Expected behavior**
Maybe see blockchain data, and try to find out why my first transaction never went through.

**Environment**
- App version  v1.2.0
- Android version 10

**Comment by zpalmtree** [comment]
I will investigate the crashing.

Regarding the failed transaction being shown, transactions that are sent but never make it to the blockchain are *meant* to be cancelled and removed from the list, but that code is kinda tricky to test so maybe there is an issue there.

Doing a rescan should get rid of any discrepancies since it will gather sent transactions just from the blockchain, but may take a while depending on when you first created/imported your wallet.

**Comment by StoopidWirez** [comment]
I've tried to rescan chain from my end with no luck, I will have the
recipient try to rescan as well and let you know if it fixes the issue

**Comment by zpalmtree** [comment]
Does the transaction hash appear in the block explorer - https://explorer.turtlecoin.lol/? A full rescan should wipe all transactions and only find fresh ones from the chain.

**Comment by StoopidWirez** [comment]
I do not have access to the txn hash to find out. Everytime I try to view
the hash/additional details the app suddenly crashes.

**Comment by StoopidWirez** [comment]
This is all the info between the two wallets relating to the lost txn I
have. If any txn is clicked in an attempt to view details the app crashes.
Both users are experiencing the same issue.

The latest 50 trtl txn had no issue going through to the recipients wallet.
The original (much larger) txn shows as being sent from my wallet (and coin
is gone) but does not show from their side, even after a resync on both ends

**Comment by zpalmtree** [comment]
For now I would recommend importing and syncing your wallet in [zedwallet](https://github.com/turtlecoin/turtlecoin/releases/tag/v1.0.0) or [proton](https://getproton.org/) to be certain of what has happened to your transaction until I have time to investigate this.

**Comment by zpalmtree** [comment]
Hi, this is now fixed in v1.2.1, thanks for your report. It's currently being reviewed by google for deployment.

**Comment by StoopidWirez** [comment]
Thanks much! I'll double check everything once it's released.

**Comment by StoopidWirez** [comment]
5 stars on the update! I still have the missing coin issue however. I have txns details on my end but the recipient doesn't show the txns ever happening. Not sure if that should be covered here or somewhere else though. Thanks for all of your help so far!

**Comment by zpalmtree** [comment]
> 5 stars on the update! I still have the missing coin issue however. I have txns details on my end but the recipient doesn't show the txns ever happening. Not sure if that should be covered here or somewhere else though. Thanks for all of your help so far!

If you can now view the hash, can you find it on the block explorer? If it's on the block explorer, it's certainly on the chain, so the only possible remaining issues would be somehow it got sent to the wrong address, or your recipient is doing something wrong.

If you find it on the explorer, the recipient can use the 'Check Transaction Screen' at the bottom of the page to verify that the transaction was sent to them, they just need to enter their private view key and address and it should show any matching outputs like so:

![image](https://user-images.githubusercontent.com/22151537/105206583-71c88a00-5b3e-11eb-81bd-c2efe1b70669.png)

**Comment by zpalmtree** [comment]
Closing, please open a new issue or visit our discord (https://discord.gg/turtlecoin) if you are still having issues with your transaction.
